permissions:
  contents: read
env:
  RUST_LOG: "info"
on:
  schedule:
    - cron: "7 7 1,7,20 * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: rolling
jobs:
  nightly:
    runs-on: ${{ vars.RUNNER }}
    name: ubuntu / nightly
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ubicloud/rust-cache@v2
        with:
          cache-on-failure: "true"
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo test --locked
        run: cargo test --locked --all-features --all-targets
